-- V2 shipped placeholder BCrypt hashes that don't actually verify against
-- the plaintext "password". This migration replaces them with a real
-- BCryptPasswordEncoder().encode("password") output — generated by running
--   ./gradlew -q hash --args="password"
-- Only the seeded dev accounts are touched. Users created after V2 are
-- unaffected.

UPDATE users
   SET password_hash = '$2a$10$wKn8Nxjr0R5uFqdl.iSFXOs8YPEamA5gK4KcoxQcOYQwW/idaItv6'
 WHERE id IN (1, 2, 3, 100, 101, 102);
